### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by cursedcoder** [Sch3lp/twitch-smart-tv#1]
Hi Sch3lp,

is this application ready to use? 
I just didn't find any instructions how to setup it on TV, so I just imported repo as smarttv base application in SDK 4.5 and have white screen in emulator.

**Comment by Sch3lp** [comment]
It's not ready to use just yet. Haven't had the time to work on it for a
while now. :(

On 13-okt.-2013, at 02:52, Evgeniy Guseletov notifications@github.com
wrote:

Hi Sch3lp,

is this application ready to use?
I just didn't find any instructions how to setup it on TV, so I just
imported repo as smarttv base application in SDK 4.5 and have white screen
in emulator.

—
Reply to this email directly or view it on
GitHubhttps://github.com/Sch3lp/twitch-smart-tv/issues/1
.

**Comment by Sch3lp** [comment]
I added a Trello board with ongoing tasks to show how far I am, building this app: https://trello.com/b/EqFt55tS/twitch-tv-smarttv-app
Link is also in the README.md now.
