### ISSUE TITLE
Purple screen with Twitch logo in upper left

### ISSUE THREAD

**Issue by Candagrm** [Sch3lp/twitch-smart-tv#10]
Trying to run the app on a UN46D8000.  The app launches but only displays a purple background with the Twitch.tv logo in the upper left of the screen.

**Comment by Sch3lp** [comment]
What I don't understand is how you do feel inclined to post this "issue", and yet you do not feel inclined to first read the main page (README.md), or the issues. _sigh_

Anyway, this app is definitely not production-ready, hence the lack of milestone.
See [https://github.com/Sch3lp/twitch-smart-tv](the main page) or even this [https://github.com/Sch3lp/twitch-smart-tv/issues/1](this issue).
