### ISSUE TITLE
missing "promise.then" call when initializing the $scope.streams

### ISSUE THREAD

**Issue by vmazur** [Sch3lp/twitch-smart-tv#11]
--- a/app/scripts/app.js
+++ b/app/scripts/app.js
@@ -21,10 +21,17 @@ angular.module('twitchSmartTvApp', ['twitchServices', 'samsungServices', 'ngRout
       .when('/', {
         templateUrl: 'views/main.html',
         controller: function ($scope, Streams) {
-          $scope.streams = Streams.getAll();
-           var promise = Streams.getAll();
-           promise.then(function(streams) {
-              $scope.streams = streams;
-            }, function(reason) {
-              alert('Failed: ' + reason);
-            }, function(update) {
-              alert('Got notification: ' + update);
-            });
       }
     })
     .otherwise({
       redirectTo: '/'
     });
-  }]);
  \ No newline at end of file
-  }]);

**Comment by Sch3lp** [comment]
Thanks.
